FROM python:3.13.5-slim

RUN pip install --no-cache-dir gradio huggingface_hub

WORKDIR /app

COPY frontend_azure.py /app/
COPY backend_azure.py /app/

EXPOSE 7860

CMD ["python", "frontend_azure.py"]