FROM python:3.13.5-slim

RUN pip install --no-cache-dir gradio huggingface_hub

WORKDIR /app

COPY src/frontend_aws.py /app/
COPY src/backend_aws.py /app/

EXPOSE 7860

CMD ["python", "frontend_aws.py"]