services:
  backend:
    image: dashlipsey/songbird_backend:latest
    environment:
      HF_TOKEN: ${HF_TOKEN}
    container_name: songbird_backend
    ports:
      - '22031:8000'
    networks:
      - songbird_net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  frontend:
    image: dashlipsey/songbird_frontend:latest
    container_name: songbird_frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - '22030:7860'
    networks:
      - songbird_net
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok3
    depends_on:
      - frontend
    command: http frontend:7860
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
    - "22032:4040"
    networks:
      - songbird_net
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor3
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    networks:
      - songbird_net
    restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter3
    command:
      - --path.rootfs=/host
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    volumes:
      - /:/host:ro
    pid: host
    networks:
      - songbird_net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus3
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - '22033:9090'
    depends_on:
      - frontend
      - backend
      - cadvisor
      - node-exporter
    networks:
      - songbird_net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana3
    ports:
      - "22035:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - songbird_net
    restart: unless-stopped

networks:
  songbird_net:
    driver: bridge

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
